### ISSUE TITLE
[Feature]: task list 등록 필요.

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/test_repo#54]
### Story

현재 github beta system인 task list 기능을 우리 프로젝트에 도입해야한다. 각각의 microservice에 대한 세부적인 issue들을 관리하기 용이해질 것 이다.

### Task completion criteria

- [x] task list wait list 등록
- [x] task list 사용 가능
- [x] task list로 프로젝트 설계
- [x] master에 대한 pull request branch name validation
- [x] master에 대한 merge가 아닌 경우에도 관련 issue가 close 되도록 설정
- [x] master에 대한 pull request는 모든 task가 완료된 경우에만 가능

**Comment by cryscham123** [comment]
현재 task list beta 사용자 모집이 중단된 상태이기 때문에, 일반 issue template으로 구현해야함

**Comment by cryscham123** [comment]
master에 대한 merge가 이루어지지 않은 issue를 자동으로 close할 이유는 없음.
대신 issue의 task가 모두 완료됨으로 체크되면 자동으로 close하는 logic이 필요함.
