### ISSUE TITLE
login fail

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/test_repo#87]
### What happened?

로그인이 잘 안됩니다.

### Relevant log output

```shell
what
```

### Task completion criteria

- [ ] 로그인 요청을 성공적으로 처리해야 합니다.
- [ ] 비밀번호 암호화가 이루어져야 합니다.
- [ ] 하마도 로그인이 가능해야합니다.
