### ISSUE TITLE
login fail

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/test_repo#89]
### What happened?

로그인이 안됩니다.

### Relevant log output

```shell
zsh: command not found: asdasd
```

### Task completion criteria

- [ ] 로그인에 대한 처리가 이루어져야 합니다.
- [ ] 비밀번호가 암호화되어야 합니다.
- [ ] 하마도 로그인이 가능해야 합니다.
